### ISSUE TITLE
Logging unhandled exceptions as 500 error

### ISSUE THREAD

**Issue by alhardy** [alhardy/AppMetrics#109]
https://github.com/alhardy/AppMetrics/pull/108

**Comment by alhardy** [comment]
@djturner1984 Actually, we probably still want to throw the exception yeah? https://github.com/alhardy/AppMetrics/commit/eb524ad859152c1f849d246b162f20cc7b945207

**Comment by djturner1984** [comment]
@alhardy yeah you're right, otherwise the middleware will swallow the exception. I think if we add a `throw;` in the catch it will rethrow the exception and the finally will still execute with the 500 status code. I'll send through another PR for this
