### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by michael-x** [alhardy/AppMetrics#117]
As a first project gathering metrics I would like to set up AppMetrics reporting into InfluxDB using Grafana for visualization. To get a feeling on how everything works I wanted to set up a simple graph showing number of requests per minute for each endpoint over time.

I did find the "application.httprequests__transactions_per_endpoint" measurement in InfluxDB but I am having a hard time choosing the correct field for my graph. I kind of would have expected something like a counter that resets after being reported. Instead, the only counters I have found seem to count forever. The closest I could get is using the rate1m field. But when I have three requests in one minute and zero requests in the next, my graph is not showing three and zero. Instead it is showing a slow decay from three downwards that appears to take a lot longer than a minute.

I guess all this has to do with the reservoir feature but I'm not sure how to use that properly. After all I've got a time window of one minute during which I would like to collect data, so my assumption would be that my sliding window would be one minute. How does that translate into number of samples?

A bit of advice would be greatly appreciated and might also help others getting off to a better start.

Thanks.

**Comment by jenyayel** [comment]
I highly recommend you to watch the [video](https://www.youtube.com/watch?v=czes-oa0yik) of codahale, the creator of original AppMetric library (on which this port is based on). He explains it pretty well why average is bad, why you cannot just collect/store every measurement in application and many other things that you will give you an idea why this library and other similar contains a decent amount of code.

BTW, @alhardy already created [sample dashboards](https://github.com/alhardy/AppMetrics.Samples/tree/master/grafana_dashboards) which can be good starting point for you.

**Comment by alhardy** [comment]
@michael-x  in terms of web metrics to influxdb, try importing the [generic web dashboard](https://github.com/alhardy/AppMetrics.Extensions.InfluxDB/tree/dev/visualization/grafana-dashbaords) into grafana. There is also an equivalent for ES. That should give you most, if not all metrics you get from other paid APM solutions.

Counters can be reset on reporting, please see the [docs](https://alhardy.github.io/app-metrics-docs/getting-started/metric-types/counters.html)

Reservoirs are for sampling data and used for Histograms, more info and external references in the docs.

As @jenyayel mentioned you can also check the [sample repo](https://github.com/alhardy/AppMetrics.samples), and yep the codehal dropwizard metrics video is a great start. There's also a bunch of "getting started" info on the docs site.

**Comment by michael-x** [comment]
@jenyayel thanks for the video link. It's a good introduction on the subject. One of the things that I took from the video is the "sense of recency" which is exactly what I was missing. Looking at the following graph from the generic dashboard showing graphs for the "last 5 minutes" you can see that the rpm value are still decaying, even if there has been zero requests for way more than an hour. The values that are graphed are tiny, but meaningless.

![image](https://cloud.githubusercontent.com/assets/1742876/25176511/a278633e-24fe-11e7-8986-87d57ff67ba3.png)

@alhardy unfortunately there is no description on the requirements for each of the dashboards. Some of them assume that you have a datasource named "Influx", mine was called something else. The generic dashboard is a little easier to use as you can pick the datasource, but even then it assumes that you've got an "env" tag and an "app" tag to select from. The "Organizing Metrics" page uses "app_name" instead of "app" for the application name. There are a couple of hurdles that one must take to get from zero to working dashboard.

You've mentioned that counters can be reset on reporting and looking at the docs I can see how I would have AppMetrics reset my counters, if I define my own counters. How would I change the behaviour of counters created by the middleware?

**Comment by alhardy** [comment]
@michael-x values will decay to zero, you can play with alpha value and sample size of the Exponentially Decaying Resevoir, you could also adjust the grafana graph to set a Y-Min value and adjust the decimals show to your desire.

The dashbaords in the samples repo are just **samples** which I've used for testing and as a playground, not sure how you are wanting to re-purpose those those? Yes datasources in the sample dashbaords are tied to the sample apps as they haven't be built for anything other than being demos and for testing.

Re the generic dashabord, yes I've made that more generic to make it (hopefully) very easy to get started with little effort. I may at some stage script the influxdb and grafana setup using docker.

If you're not wanting to use `env` and/or `app` global tags you can just remove them from the dashbaord as well as the filtering/grouping on each graph. I think they are handy though, this has allowed me to re-use the same dashboard for all my api's across environments (uat/staging/production). For anything more specific to the app I just create a new dashboard(s) with those more app specific metrics e.g. number of user logins, emails sent or bounced etc.

`app_name` vs `app`, tags are just key values, it's really up to you to determine what tags your application needs at the end of the day. The "Organizing Metrics" page is just explaining how one can use tags etc.

The [sandbox](https://github.com/alhardy/AppMetrics/tree/dev/sandbox/App.Metrics.Sandbox) project gets you up and running only a few steps documented [here](https://github.com/alhardy/AppMetrics.Extensions.InfluxDB#grafanainfluxdb-web-application-setup) for InfluxDB and [here](https://github.com/alhardy/AppMetrics.Extensions.Elasticsearch#grafanaelasticsearch-web-application-setup) for ES.

What counters provided in the default metrics middleware are you wanting to reset? There is really only one counter provided which is an active request counter and is already being decremented, no need to reset it.

**Comment by michael-x** [comment]
@alhardy Thanks for the elaborate reply. I appreciate the work that you've obviously put into the project. The point that I wanted to make was, that although one can find almost everything that you need on the web site, but it's not a smooth experience. You tell them where to look for sample dashboards, but you don't tell them that they need to have a data source "Influx" in Grafana to use them. You tell them that there is a generic dashboard, but you don't tell them to make sure to add tags for "app" and "env". It would be great to have a walk-through from zero to working dashboard, instead of a "have a look at the samples (and put the remaining puzzle pieces together)".

Regarding alpha values: looking at https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average there seems to be a difference between the definition of the alpha value for EWMAs and what is implemented for the Exponentially Decaying Reservoir. An alpha value of 0 should mean that S(t) = S(t-1), which means the sequence should always remain on its initial value, while an alpha value of 1 should mean that S(t) = Y(t), i.e. the sequence will always show the current value. If I start with 5 requests in the first period and then don't have any requests anymore, I should see a sequence of

- 5, 5, 5, 5, ... for alpha = 0 and
- 5, 0, 0, 0, ... for alpha = 1 and
- 5.0, 2.5, 1.25, 0.625, ... for alpha = 0.5

Unfortunately this is not at all what I'm observing. No matter what value I use for alpha, the curve always looks similar.

**Comment by alhardy** [comment]
@michael-x Thanks for the feedback. 

Yes I am assuming that users are already somewhat faimilar with Grafana, I don't really want to invest my efforts in documentating how to use Grafana though, those guys have already done a great job in documenting their product. 

I don't mention the datasource for the samples because that's already configured in the sample code for which the dashboard belongs, I do however mention it for the generic dashboard which is meant for re-purposing, see ["Create a new InfluxDB Database. Keep note of this for configuring the InfluxDB reporter in your web application and configuring the InfluxDB Datasource in Grafana"](https://github.com/alhardy/AppMetrics.Extensions.InfluxDB#grafanainfluxdb-web-application-setup).

Re a walkthrough, yeah that would be great, maybe you could a blog post?

Re EWMA and Exponentially Decaying Reservoir, yes those values are different, see the `SimpleMeter` vs `DefaultForwardDecayingReservoir` implementations. If you've found an issue there, would it be possible for you to implement a unit test demonstrating for me to look at?

**Comment by jenyayel** [comment]
>  I may at some stage script the influxdb and grafana setup using docker.
Really good idea!
