### ISSUE TITLE
app.UseMetricsReporting blocks on RunReports

### ISSUE THREAD

**Issue by alhardy** [alhardy/AppMetrics#129]
Calling run reports blocks waiting for the reporter thread to finish but this is long running for the lifetime of the app.

```
lifetime.ApplicationStarted.Register(
                () =>
                {
                    reporter.RunReports(metrics, appLifetime.ApplicationStopping);
                });
```

**Comment by vinhhrv** [comment]
@alhardy  please push App.Metrics.Extensions.Middleware 1.1.1 to nuget for milestone 1.1.1
you miss it

**Comment by alhardy** [comment]
@vinhhrv pushed
