### ISSUE TITLE
Health checks not executed

### ISSUE THREAD

**Issue by benfoster** [alhardy/AppMetrics#135]
Hi,

I followed the quick start guide to get up and running in an ASP.NET Core MVC app and my health checks are not being executed.

My code is pretty much a copy/paste from your site.

**Comment by alhardy** [comment]
@benfoster are you able to show your project please, and what page of the docs are you referring too?

**Comment by alhardy** [comment]
Maybe this helps? https://github.com/alhardy/AppMetrics.DocFx/issues/8

**Comment by benfoster** [comment]
That was the issue. Thanks.
