### ISSUE TITLE
Metrics not logged to Elastic Search / Grafana

### ISSUE THREAD

**Issue by benfoster** [alhardy/AppMetrics#138]
Hey Al,

I'm following your guide on setting up App Metrics with Elasticsearch and Grafana but am not seeing any data in ES or in the Grafana dashboard. Steps I followed:

1. Set up index "appmetrics" with mappings from [here](https://raw.githubusercontent.com/alhardy/AppMetrics.Extensions.Elasticsearch/master/visualization/App.Metrics.Sandbox-Elasticsearch-IndexAndMappingSetup.json)
2. Added the following code:

```
            services.AddMetrics()
                .AddJsonSerialization()
                .AddHealthChecks()
                .AddMetricsMiddleware()
                .AddReporting(factory =>
                {
                    factory.AddElasticSearch(new ElasticSearchReporterSettings
                    {
                        HttpPolicy = new HttpPolicy
                        {
                            FailuresBeforeBackoff = 3,
                            BackoffPeriod = TimeSpan.FromSeconds(30),
                            Timeout = TimeSpan.FromSeconds(3)
                        },
                        ElasticSearchSettings = new ElasticSearchSettings(new Uri("http://localhost:9200"), "appmetrics"),
                        ReportInterval = TimeSpan.FromSeconds(5)
                    });
                });
```

3. Hit my API a few times
4. Search the ES index (http://localhost:9200/appmetrics/_search). No results returned.

Am I missing a step?

Also, is my configuration in Grafana correct?

![image](https://cloud.githubusercontent.com/assets/827305/25724920/8b73f1d0-3115-11e7-9e9f-e8e74ab8710e.png)

As a side note, have you been able to set up anything as good as your Grafana dashboards in Kibana? 

Thanks for the help and for building a great tool.

**Comment by alhardy** [comment]
@benfoster that looks correct, there is a sandbox project you can use for reference https://github.com/alhardy/AppMetrics.Extensions.Elasticsearch/tree/dev/sandbox/App.Metrics.Elasticsearch.Sandbox, also note the `server` and `app` tags https://github.com/alhardy/AppMetrics.Extensions.Elasticsearch/blob/dev/sandbox/App.Metrics.Elasticsearch.Sandbox/Startup.cs#L77. These will probably be moved in a feature release to be tagged by default.

I'm using Kibana for app logs, haven't yet looked at Timelion but I hear that'll be awesome. I like Grafana for it's simplicity in plotting timeseries, but that's a personal preference. 

If you do setup some Kibana dashboards it would be awesome if you could share, I'm trying to get the Graphite report released on the moment.

**Comment by benfoster** [comment]
I'm running grafana and ES within docker using [this project] as it was easier to get everything up and running, that's why grafana has to point to the internal docker IP. In any case, shouldn't I see the data within ES?

Is there any logging I can enable to see if the requests to ES are failing?

I've added the tags, I'm assuming they're for filtering in the dashboard, but still no dice.

Thanks

**Comment by alhardy** [comment]
Yeah configure a logger of your choice with Microsoft's logging and enable it at a Trace level

**Comment by alhardy** [comment]
@benfoster your issue is likely the version of ES you're using, try version [5.4.0](https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.zip)
