### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by jwaimann** [alhardy/AppMetrics#139]
Hello, I'm new using this library for net core, I followed steps under Getting Started guide, regarding Startup.cs file. Also created a class AppMetricsRegistery declaring just a TimerOptions SampleTimer, and then in my attemp to use IMetrics instance (I assume it is injected in the controller), the following exception is thrown in running time:

> An unhandled exception occurred while processing the request.
InvalidOperationException: Could not create an instance of type 'App.Metrics.IMetrics'. Model bound complex types must not be abstract or value types and must have a parameterless constructor.

Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinder.CreateModel(ModelBindingContext bindingContext)

Stack:

    InvalidOperationException: Could not create an instance of type 'App.Metrics.IMetrics'. Model bound complex types must not be abstract or value types and must have a parameterless constructor.
        Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinder.CreateModel(ModelBindingContext bindingContext)
        Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinder+<BindModelCoreAsync>d__4.MoveNext()
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        Microsoft.AspNetCore.Mvc.Internal.DefaultControllerArgumentBinder+<BindModelAsync>d__8.MoveNext()
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        Microsoft.AspNetCore.Mvc.Internal.DefaultControllerArgumentBinder+<BindArgumentsCoreAsync>d__6.MoveNext()
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
        Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
        Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeAsync>d__20.MoveNext()
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware+<ExecuteWithFilter>d__7.MoveNext()
        System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by alhardy** [comment]
@jwaimann  can you compare what you have to one of the sandbox projects eg https://github.com/alhardy/AppMetrics.Extensions.InfluxDB/tree/dev/sandbox/App.Metrics.InfluxDB.Sandbox  or post sample code showing the issue please.
