### ISSUE TITLE
Time(Action action) method is empty in NullTimer class

### ISSUE THREAD

**Issue by mikefonted** [alhardy/AppMetrics#140]
Hi,
It seems these two methods should run 'action();', but the first one is missing it right now:
```
public void Time(Action action) { }
public void Time(Action action, string userValue) { action(); }
```
Or it's me who is missing something that I don't get yet?

BTW, the same happens in NullApdex with `public void Track(Action action) { }`, just in case.

**Comment by alhardy** [comment]
@mikefonted yep that's a bug, fix will be in next release.
