### ISSUE TITLE
Tagging at runtime and return T

### ISSUE THREAD

**Issue by mikefonted** [alhardy/AppMetrics#151]
Hi,

I have tried tags with the Provider and everything I have found is find, but now, I think I should use them at runtime with the Measure, like you say in [docs](http://app-metrics.io/getting-started/fundamentals/organizing-metrics.html#tagging-at-runtime).

However, I have found that, for example, there is no implementation for [IMeasureTimerMetrics](https://github.com/alhardy/AppMetrics/blob/dev/src/App.Metrics/Timer/Abstractions/IMeasureTimerMetrics.cs) which let me return `T` as an [ITimer](https://github.com/alhardy/AppMetrics/blob/dev/src/App.Metrics/Timer/Abstractions/ITimer.cs) does with the Provider if I pass a `Func<T>` as a parameter.

To make it clearer, this is what I can do now (simplified):
```
TimerOptions sqlPerformance = new TimerOptions
{
    Name = "sql",
    DurationUnit = TimeUnit.Milliseconds,
    Tags = new MetricTags("type", "update")
};
var providerTimer = metrics.Provider.Timer.Instance(sqlPerformance);
var value = providerTimer.Time(() => { return 1; } );
```

This is what I would like to do (instead of declaring a Timer instance everytime):
```
TimerOptions sqlPerformance = new TimerOptions
{
    Name = "sql",
    DurationUnit = TimeUnit.Milliseconds
};
var value = metrics.Measure.Timer.Time(sqlPerformance, new MetricTags("type", "update"), () => { return 1; });
```

Am I trying something that I should not? Or does it make sense what I request?

**Comment by alhardy** [comment]
What are you wanting do with the timer instance returned after already timing your action?

If you just want the timer instance, you can resolve (with tags) using the provider.

**Comment by mikefonted** [comment]
Sorry, maybe I should have explained it better.

I think that now I do not need the timer instance because I prefer tagging at runtime. So, I would like to replace the Provider and instead, use the Measure. But, there is not a Measure timer which accepts a `Func<T>` as a parameter and returns the results of that function after timing it.

Something like the following, I guess it would resolve the previous second example (which is what I want):
`T Time<T>(TimerOptions options, MetricTags tags, Func<T> action);`

**Comment by alhardy** [comment]
Can you use a Timer in a using statement instead? https://github.com/alhardy/AppMetrics/blob/dev/test/App.Metrics.Facts/Managers/DefaultTimerManagerTests.cs see the 'can_time_in_using_when_multidimensional_with_user_value' test

**Comment by mikefonted** [comment]
That should do the trick, then. Thanks.

BTW, would not you prefer to keep Provider and Measure as similar as possible? I mean, if they try to do the same thing (with the difference that one returns an instance and the other one does not)... Why do not try to keep their methods and its parameters as similar as possible too?

**Comment by alhardy** [comment]
Cool.

They could be similar, open to suggestions? I'm in the middle of a massive refactor, it's a good time for breaking changes as I'm upgrading to .net standard and asp.net core 2.0 atm.

What's the difference between returning an instance and just measuring the metric? It can be useful to get a metric instance(s) to measure more complex metrics, see [here](https://github.com/alhardy/AppMetrics.Samples/blob/master/src/Api.Sample/Controllers/ValuesController.cs#L83) for example.

**Comment by tmsf** [comment]
Hi, 
I've have a similar issue, I was using your default metrics, but I wanted to add an extra tag dependent on the request's payload.
I've created a custom ```TimerOptions``` to add my custom tags. But I ended up losing the status codes info.

```
var requestTimer = new TimerOptions
{
    Name = "Request Duration seconds",
    MeasurementUnit = Unit.Requests,
    DurationUnit = TimeUnit.Seconds,
    RateUnit = TimeUnit.Seconds
};
            
var additionalMetricTags = new MetricTags("action", action);     

using(var metric = _metrics.Measure.Timer.Time(requestTimer, additionalMetricTags))
{
  await next();
}
```

Ultimately, my intent is to extend your default metrics by adding runtime tags to them, not to use custom ones.
Is this possible?

**Comment by alhardy** [comment]
`IMetrics` is not tied to `HttpContext` in anyway, you'll have to re-add the tags you require from the `HttpContext`
