### ISSUE TITLE
Support for Telegraf + UDP

### ISSUE THREAD

**Issue by seanamosw** [alhardy/AppMetrics#152]
Currently connecting to InfluxDB via HTTP is well supported.
Another common setup with InfluxDB is to distribute Telegraf agents across hosts which then submit the data to database.

Telegraf supports a variety of protocols however UDP can be very beneficial as it is fire and forget.

**Comment by alhardy** [comment]
Happy to add support for this after v2.0.0 which I've only just started, more than happy for you to give it a crack and PR.

Can you request this feature in the [InfluxDB](https://github.com/alhardy/AppMetrics.Extensions.InfluxDB) repo.

**Comment by alhardy** [comment]
Moved to https://github.com/AppMetrics/InfluxDB/issues/17
