### ISSUE TITLE
.NET Standard 2.0

### ISSUE THREAD

**Issue by alhardy** [alhardy/AppMetrics#157]

**Comment by jenyayel** [comment]
Alan, why it would be a breaking change?

**Comment by alhardy** [comment]
Slight difference in platform support between standard 1.6 and 2.0, mostly should be fine. Unless I'm missing something.

https://docs.microsoft.com/en-us/dotnet/standard/library

**Comment by alhardy** [comment]
Need VS 2017 Preview Image on AppVeyor - https://github.com/appveyor/ci/issues/1549

**Comment by alhardy** [comment]
`Microsoft.Extensions.PlatformAbstractions` has been removed in dotnet core 2.0 - see write up [here](http://hishambinateya.com/goodbye-platform-abstractions)

**Comment by alhardy** [comment]
Middleware packages as of asp.net core preview 1 require `netcoreapp2.0`, looks like that may change to `netstandard2.0` in the next release of asp.net core
