### ISSUE TITLE
Add degradedOnError parameter to the HealthCheckFactoryExtensions methods

### ISSUE THREAD

**Issue by lecaillon** [alhardy/AppMetrics#172]
Hi,

Methods define in the `HealthCheckFactoryExtensions` class are really usefull. 
Still, when the check fails, it always call HealthCheckResult.Unhealthy().

Sometimes I just want to degrade the health status.

Could it be interresting to add a HealthCheckStatus parameter to all the methods of that class to define the check status we want in case of failure ?

Sommeting like : (_with perhaps a better param name_)

``` c#
public static IHealthCheckFactory RegisterHttpGetHealthCheck(
            this IHealthCheckFactory factory,
            string name,
            Uri uri,
            TimeSpan timeout,
            CancellationToken token = default(CancellationToken),
            HealthCheckStatus failStatus = HealthCheckStatus.Unhealthy)
        {
            ...
        }
```

**Comment by alhardy** [comment]
Thanks @lecaillon, yeah that could be useful.

I'm concentrating on a 2.0.0 release atm. I've scheduled adding this as part of the next release.

Happy to take a PR on the current version otherwise.

**Comment by lecaillon** [comment]
I'm working on it :smiley:
Finally the signature would be :

``` c#
        public static IHealthCheckFactory RegisterHttpGetHealthCheck(
            this IHealthCheckFactory factory,
            string name,
            Uri uri,
            TimeSpan timeout,
            CancellationToken token = default(CancellationToken),
            bool degradedOnError = false)
        {
              ...
        }
```

Because if the check fails, nobody wants to use the HealthCheckStatus.Healthy or HealthCheckStatus.Ignored. And I do not want to add this unecessary guard code.
