### ISSUE TITLE
Using DI in metrics extension methods

### ISSUE THREAD

**Issue by MrSmoke** [alhardy/AppMetrics#181]
I've written my own `IReporterProvider` and need to pull an existing service from DI to construct it, however when calling `AddReporting` there is no way to actually resolve any existing services. 

I notice that you actually have an instance of `IServiceProvider` in the body of the function here: https://github.com/alhardy/AppMetrics/blob/463053fea7e1ea22b973351690c246690ddfd2fe/src/App.Metrics/DependencyInjection/BuilderExtensions/MetricsHostBuilderExtensionsOptional.cs#L112 so maybe it could follow the `IApplicationBuilder` pattern and have `factory.ApplicationServices`? Same could be done for `AddHealthChecks`

Eg

```cs
.AddReporting(factory =>
{
    var otherService = factory.ApplicationServices.GetRequiredService<IOtherService>();
    var reportProvider = new MyReportProvider<MyPayload>(myPayloadBuilder, otherService);

    factory.AddProvider(reportProvider);
});
```

**Comment by alhardy** [comment]
Yep, all this is currently being refactored, a similar approach to the [health refactoring](https://github.com/AppMetrics/Health/blob/dev/src/App.Metrics.Health/HealthChecksServiceCollectionExtensions.cs#L36) will be available for metrics and reporting. This follows AspNetCore MVC conventions.

An alpha version isn't too far off.

I'd prefer not to make such significant changes to the current version, can you think of a work around to get you by for now?

**Comment by MrSmoke** [comment]
No worries. Most of the objects are singletons anyway, so I'm creating them outside of DI, registering those instances and using them again in App Metrics

**Comment by alhardy** [comment]
Closing this as https://github.com/AppMetrics/Reporting/issues/38 will fix
