### ISSUE TITLE
Extend options classes

### ISSUE THREAD

**Issue by TaffarelJr** [alhardy/AppMetrics#182]
I want to add a few custom settings to my AppMetrics config sections (just for cosmetics; it's the most relevant location in this case). I extended the `AspNetMetricsOptions` class and added some properties, then wired it into the DI container so _it's_ used instead of the original (base) class.

It works great.

Now I'd like to do the same thing with the `AppMetricsOptions` class, but it's `sealed`. I can work around that of course, but it's ugly and requires quite a bit more effort. Is there any particular reason why it's sealed? And/or, is there any chance of getting that restriction lifted in the next release? (Sooner would be nice!)

**Comment by alhardy** [comment]
No particular reason why it's sealed, yeah I'll remove that in the next version.

Maybe you could do something like [this](https://github.com/AppMetrics/Health/blob/dev/src/App.Metrics.Health.Formatters.Json/Internal/HealthJsonOptionsSetup.cs), where you define you custom options which sets a an `AppMetricsOptions` property?

**Comment by TaffarelJr** [comment]
I'll give that a shot, thanks!
