### ISSUE TITLE
Listen on different port for metrics enpoints?

### ISSUE THREAD

**Issue by Gavangh** [alhardy/AppMetrics#184]
Hi,

Awesome library! One quick question; is it possible to have the metrics end points listening on a different port? It would make it significantly easier to F/W the metrics endpoints from the public internet (i.e. only allow port 80 from load balancer, them [metrics port] from the LAN.

Failing that, are there any other mechanisms I could use to ensure the metrics endpoints aren't discoverable from the internet?

Thanks

**Comment by alhardy** [comment]
Thanks for the feedback.

I've thought about adding some type of hook to do authz, at the moment the port isn't configurable either. 

You could probably just add your own middle before the metrics middleware is registered performing some type of authz when /metrics is requested.

I'll add support to specify a port in the V2 release.

**Comment by Gavangh** [comment]
Great, thanks.

For now, I've changed the kestrel bindings to listen on two ports, then written some middleware which only permits requests to the metrics endpoint via the health port.

More testing required, but seems to work for me

**Comment by alhardy** [comment]
Done in https://github.com/AppMetrics/AspNetCore see commit above
