### ISSUE TITLE
Autofac support

### ISSUE THREAD

**Issue by pshrosbree** [alhardy/AppMetrics#186]
Autofac support would be very useful. The Microsoft extensions are all very well, but the container is limited, and while it is possible for Autofac to support Microsoft extensions DI, it is somewhat messy. I am not sure how one would go about this.

**Comment by alhardy** [comment]
I'm a long time Autofac user myself, however now with DI being a first class citizen, I'm happy to go with Microsoft's implementation and just implement extensions where necessary but do try to keep registrations simple.

Have you tried this? - https://github.com/autofac/Autofac.Extensions.DependencyInjection

**Comment by pshrosbree** [comment]
Yes, I have, and this is the messy solution I mentioned. 😉
The Microsoft DI is not yet capable of some of the requirements we have for DI of some environments, such as Service Fabric. However this thread was mainly just to raise the issue. I am currently using Autofac's support for Microsoft.Extensions.
Thanks Al

**Comment by alhardy** [comment]
Right :) Let me have a think about it. I really don't want to go down the path of having an Autofac `IServiceCollection` implementation or some type of container abstraction myself. Last I looked Service Fabric requires MEF type DI, is that the type of thing your using Autofac for? 

Also should note that App Metrics doesn't do any Service Locator type dependency resolution.

Very interested to know a bit more about how you're using App Metrics with Service Fabric?

**Comment by pshrosbree** [comment]
Perhaps a good way to address this to have App.Metrics take no dependency on and DI container, and rather publish separate packages for different DI frameworks, much the way other packages, such AutoFixture, do.

And while you're (we're?) about it, use CLog (https://github.com/conformal/clog) to avoid the direct dependency on Microsoft.Extensions.Logging.

**Comment by alhardy** [comment]
Re no DI container dependency, yeah fair point, I do have a couple of .NET "classic" applications using Autofac and App Metrics and it is dirty having to configure a 'ServiceCollection' just for AppMetrics. I may just end up leaving the 'IServiceCollection' stuff in the AspNet Core App Metrics package since one would already have that dependancy.

By MEF style rather than dynamic proxies and interceptors I meant component discovery, either way I get your problem.

I'll look at this sometime over the next few weeks.

Thanks for sharing your usage, happy to see App Metrics used in different environments!

**Comment by alhardy** [comment]
This is what I have so far for bootstrapping, no container ;)

```
AppMetrics.Metrics = new MetricsConfiguration()
                .Options.Configure(options =>
                {
                    options.DefaultContextLabel = "Testing";
                    options.MetricsEnabled = true;
                    options.OutputMetricsFormatters.Add(new MetricsJsonOutputFormatter());
                })
                .SampleWith.AlgorithmR()
                .Filter.ByIncludingOnlyTypes(MetricType.Counter)
                .TimeWith.StopwatchClock()
                .Create(); // returns IMetrics
```

**Comment by alhardy** [comment]
Also added `LibLog` as a private asset

**Comment by pshrosbree** [comment]
I like it!
:)

**Comment by alhardy** [comment]
There's now two approaches to bootstrap without a container

- To customise: https://github.com/alhardy/AppMetrics/blob/2.0.0-refactoring/src/App.Metrics/AppMetrics.cs#L26
- To get the defaults: https://github.com/alhardy/AppMetrics/blob/2.0.0-refactoring/sandbox/MetricsSandbox/Host.cs#L123

May still change slightly before releasing, but with this approach it's probably not necessary to include an Autofac extension package

**Comment by pshrosbree** [comment]
That'll work.
Thanks for accommodating this.

What do you anticipate your release time frame is, roughly?

**Comment by alhardy** [comment]
Another 2-4 weeks probably for an alpha, given the free time I have atm

**Comment by pshrosbree** [comment]
Thanks Alan

**Comment by alhardy** [comment]
@pshrosbree 2-4 weeks is out the window unfortunately, mostly day job in the way :)

**Comment by pshrosbree** [comment]
I gathered as much. All good.

Thanks for the link to [Add support for reporting application metrics via logging](https://github.com/aspnet/Logging/issues/708)

It may take a while for them to decide what to do, and regardless of the approach, I like the interface of AppMetrics. Perhaps when, and if, they decide on a design, it can be used as a reporter. It may be necessary to have a type of reporter that can be injected before aggregation to support sinks that like to get all events. We currently have this scenario, in which an aggregating service runs on the same box. It is a pretty stupid aggregating service, so I prefer using the aggregating features in AppMetrics. I am sure there is a way forward with AppMetrics.

**Comment by alhardy** [comment]
@pshrosbree just pushed an alpha release of 2.0, [documentation](https://www.app-metrics.io/getting-started/) has been updated, 1.0 docs are [here](https://alhardy.github.io/app-metrics-docs/)

**Comment by pshrosbree** [comment]
Great news. I'll try it out this week.
