### ISSUE TITLE
[Feature] Reporter for Graphite/Carbon DB port 2003 or 2004

### ISSUE THREAD

**Issue by paulkling** [alhardy/AppMetrics#67]
What would be your thoughts on reporter that send data to carbon db for graphite.

I really like the way graphite data sources  (carbon) show up in Grafana

![graphite_query1](https://cloud.githubusercontent.com/assets/1531911/22087748/5c5b6f7c-dda5-11e6-9603-e86a4ec62a66.gif)

**Comment by alhardy** [comment]
@paulkling yeah definitely. Im making contract changes atm and still have some testing to do before a v1 stable release goes out, I wont be looking at new features untill then though. An RC should go out in a couple of weeks.

Certainly would be happy to have a PR on this in the meantime.

**Comment by alhardy** [comment]
Reporters live [here](https://github.com/alhardy/AppMetrics.Reporters), won't be looking at graphite until after the initial stable version is released

**Comment by alhardy** [comment]
Moved to reporting repo https://github.com/alhardy/AppMetrics.Reporters/issues/8
