### ISSUE TITLE
Elasticsearch sink

### ISSUE THREAD

**Issue by mwjackson** [alhardy/AppMetrics#94]
Its mentioned in the README but I can't see any implementation where we can point the data to ES. I may have some time to help with this in the next few weeks for a PR. Where should I look to begin? Any pointers that will make implementing this easier?

**Comment by alhardy** [comment]
There's no implementation of an ES reporter as yet, but yes a PR for this would be great 👍 

I've implemented a [reporter for InfluxDB](https://github.com/alhardy/AppMetrics.Reporters/tree/1.0.0/src/App.Metrics.Extensions.Reporting.InfluxDB) that should help you get started

**Comment by mwjackson** [comment]
Ok, I'll take a look once I get our cluster up and running
